/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import com.mycompany.practica.Aeropuerto;
import com.mycompany.practica.Autobus;
import com.mycompany.practica.Avion;
import com.mycompany.practica.HiloSuperior;
import com.mycompany.practica.Listas;
import com.mycompany.practica.Log;
import com.mycompany.practica.ServidorAeropuerto;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

/**
 *
 * @author elia3
 */
public class Parte1 extends javax.swing.JFrame {

    /**
     * Creates new form ventana2
     */
    Aeropuerto aeroM;
    Aeropuerto aeroB;
    Listas aeroviaMB, aeroviaBM;
    Log log = new Log("evolucionAeropuerto.txt");
    HiloSuperior superior = new HiloSuperior();
    public Parte1() throws RemoteException {
        initComponents();
        
        Avion av;
        Autobus bus;
        
        aeroviaMB = new Listas(jTextAMB);
        aeroviaBM = new Listas(jTextABM);
        aeroM = new Aeropuerto(log, aeroviaMB,aeroviaBM,jTextTCM,jTextTAM,jTextPasajerosM,jTextHangarM, jTextAreaEstcM, jTextPE1M, jTextPE2M, jTextPE3M, jTextPE4M, jTextPE5M, jTextPE6M, jTextARM,jTextP1M,jTextP2M, jTextP3M, jTextP4M,jTextAMB,jTextTallerM);
        aeroB = new Aeropuerto(log, aeroviaBM, aeroviaMB, jTextTCB,jTextTAB,jTextPasajerosB,jTextHangarB, jTextAreaEstcB, jTextPE1B, jTextPE2B, jTextPE3B, jTextPE4B, jTextPE5B, jTextPE6B, jTextARB, jTextP1B, jTextP2B, jTextP3B, jTextP4B, jTextABM,jTextTallerB);
        for (int i=1; i<8001; i++)
        {
            if (esPar(i)){
                av=new Avion(i,aeroM, aeroB, log, superior);
                av.start();
            }else{
                av=new Avion(i,aeroB, aeroM, log, superior);
                av.start();
            }
            
        }
        
        for(int i = 1; i < 4001; i++){
            if(esPar(i)){
                bus = new Autobus(i,aeroM, log, superior);
                bus.start();
            }else{
                bus = new Autobus(i,aeroB, log, superior);
                bus.start();
            }
        }  
        
        iniciarServidorMadrid();
        iniciarServidorBarcelona();
    }
    
    private boolean esPar(int num){
        return (num%2 == 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextHangarM = new javax.swing.JTextField();
        LabelHangarM = new javax.swing.JLabel();
        LabelAEM = new javax.swing.JLabel();
        jTextAreaEstcM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextHangarB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextAreaEstcB = new javax.swing.JTextField();
        LabelTCM = new javax.swing.JLabel();
        LabelTallerM = new javax.swing.JLabel();
        LabelPasajerosM = new javax.swing.JLabel();
        LabelTAM = new javax.swing.JLabel();
        LabelARM = new javax.swing.JLabel();
        LabelPE1M = new javax.swing.JLabel();
        LabelPE2M = new javax.swing.JLabel();
        LabelPE3M = new javax.swing.JLabel();
        LabelPE4M = new javax.swing.JLabel();
        LabelPE6M = new javax.swing.JLabel();
        LabelPE5M = new javax.swing.JLabel();
        LabelP1M = new javax.swing.JLabel();
        LAbelP2M = new javax.swing.JLabel();
        LabelP3M = new javax.swing.JLabel();
        LabelP4M = new javax.swing.JLabel();
        jTextTCM = new javax.swing.JTextField();
        jTextTAM = new javax.swing.JTextField();
        jTextPasajerosM = new javax.swing.JTextField();
        jTextTallerM = new javax.swing.JTextField();
        jTextPE1M = new javax.swing.JTextField();
        jTextPE2M = new javax.swing.JTextField();
        jTextPE3M = new javax.swing.JTextField();
        jTextPE4M = new javax.swing.JTextField();
        jTextPE5M = new javax.swing.JTextField();
        jTextPE6M = new javax.swing.JTextField();
        jTextARM = new javax.swing.JTextField();
        jTextP1M = new javax.swing.JTextField();
        jTextP2M = new javax.swing.JTextField();
        jTextP3M = new javax.swing.JTextField();
        jTextP4M = new javax.swing.JTextField();
        jTextTallerB = new javax.swing.JTextField();
        jTextPE1B = new javax.swing.JTextField();
        jTextPE2B = new javax.swing.JTextField();
        jTextPE3B = new javax.swing.JTextField();
        jTextPE4B = new javax.swing.JTextField();
        LabelTallerB = new javax.swing.JLabel();
        jTextPE5B = new javax.swing.JTextField();
        jTextPE6B = new javax.swing.JTextField();
        jTextARB = new javax.swing.JTextField();
        LabelARM1 = new javax.swing.JLabel();
        jTextP1B = new javax.swing.JTextField();
        LabelPE1M1 = new javax.swing.JLabel();
        LabelPE2M1 = new javax.swing.JLabel();
        LabelPE3M1 = new javax.swing.JLabel();
        LabelPE4M1 = new javax.swing.JLabel();
        LabelPE6M1 = new javax.swing.JLabel();
        LabelPE5M1 = new javax.swing.JLabel();
        LabelP1M1 = new javax.swing.JLabel();
        LAbelP2M1 = new javax.swing.JLabel();
        LabelP3M1 = new javax.swing.JLabel();
        LabelP4M1 = new javax.swing.JLabel();
        jTextP2B = new javax.swing.JTextField();
        jTextP3B = new javax.swing.JTextField();
        jTextP4B = new javax.swing.JTextField();
        LabelPasajerosB = new javax.swing.JLabel();
        jTextPasajerosB = new javax.swing.JTextField();
        LabelTCB = new javax.swing.JLabel();
        LabelTAB = new javax.swing.JLabel();
        jTextTCB = new javax.swing.JTextField();
        jTextTAB = new javax.swing.JTextField();
        LabelAMB = new javax.swing.JLabel();
        LabelABM = new javax.swing.JLabel();
        jTextAMB = new javax.swing.JTextField();
        jTextABM = new javax.swing.JTextField();
        bttParar = new javax.swing.JButton();
        bttSeguir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextHangarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHangarMActionPerformed(evt);
            }
        });

        LabelHangarM.setText("Hangar:");

        LabelAEM.setText("Area Estc:");

        jTextAreaEstcM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAreaEstcMActionPerformed(evt);
            }
        });

        jLabel3.setText("Aeropuerto Madrid");

        jLabel4.setText("Aeropuerto Barcelona");

        jLabel5.setText("Hangar:");

        jTextHangarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHangarBActionPerformed(evt);
            }
        });

        jLabel6.setText("Area Estc:");

        LabelTCM.setText("Transfers Ciudad");

        LabelTallerM.setText("Taller");

        LabelPasajerosM.setText("Nº Pasajeros en Aeropuerto ");

        LabelTAM.setText("Transfers Aeropuerto");

        LabelARM.setText("Area de Rodaje");

        LabelPE1M.setText("Puerta 1:");

        LabelPE2M.setText("Puerta 2:");

        LabelPE3M.setText("Puerta 3:");

        LabelPE4M.setText("Puerta 4:");

        LabelPE6M.setText("Puerta 6:");

        LabelPE5M.setText("Puerta 5:");

        LabelP1M.setText("Pista 1:");

        LAbelP2M.setText("Pista 2:");

        LabelP3M.setText("Pista 3:");

        LabelP4M.setText("Pista 4:");

        jTextTCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTCMActionPerformed(evt);
            }
        });

        LabelTallerB.setText("Taller");

        LabelARM1.setText("Area de Rodaje");

        LabelPE1M1.setText("Puerta 1:");

        LabelPE2M1.setText("Puerta 2:");

        LabelPE3M1.setText("Puerta 3:");

        LabelPE4M1.setText("Puerta 4:");

        LabelPE6M1.setText("Puerta 6:");

        LabelPE5M1.setText("Puerta 5:");

        LabelP1M1.setText("Pista 1:");

        LAbelP2M1.setText("Pista 2:");

        LabelP3M1.setText("Pista 3:");

        LabelP4M1.setText("Pista 4:");

        LabelPasajerosB.setText("Nº Pasajeros en Aeropuerto");

        LabelTCB.setText("Transfers Ciudad");

        LabelTAB.setText("Transfers Aeropuerto");

        LabelAMB.setText("Aerovia Madrid-Barcelona");

        LabelABM.setText("Aerovia Barcelona-Madrid");

        bttParar.setText("Detener");
        bttParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPararActionPerformed(evt);
            }
        });

        bttSeguir.setText("Reanudar");
        bttSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSeguirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(292, 292, 292))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelPasajerosM)
                        .addGap(18, 18, 18)
                        .addComponent(jTextPasajerosM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LabelARM)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextARM, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(LabelAMB)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LabelP1M)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextP1M, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LAbelP2M)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextP2M, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(44, 44, 44)
                                    .addComponent(LabelP4M)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextP4M, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LabelTAM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelTCM)
                                        .addGap(29, 29, 29)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextTCM, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jTextTAM))
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelP3M)
                                .addGap(18, 18, 18)
                                .addComponent(jTextP3M, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LabelPE1M)
                                                .addComponent(LabelPE2M)
                                                .addComponent(LabelPE3M))
                                            .addGap(26, 26, 26))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LabelAEM, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelTallerM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelHangarM))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextHangarM, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextAreaEstcM, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextPE2M, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextPE1M, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextPE3M, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(LabelPE4M)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextPE4M, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(LabelPE5M)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextPE5M, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(LabelPE6M)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextPE6M, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jTextTallerM, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelP1M1)
                                        .addComponent(LabelARM1)
                                        .addComponent(LAbelP2M1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelABM)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(LabelPasajerosB)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5)
                                                    .addComponent(LabelTallerB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextPasajerosB)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextAreaEstcB, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextHangarB, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextPE1B, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextTallerB, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextPE2B, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextPE3B, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextARB, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextP1B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextP2B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LabelP3M1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextP3B, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LabelP4M1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextP4B, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelPE1M1)
                                .addGap(229, 229, 229)
                                .addComponent(LabelPE4M1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextPE4B, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelPE3M1)
                                .addGap(229, 229, 229)
                                .addComponent(LabelPE6M1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextPE6B, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelPE2M1)
                                .addGap(229, 229, 229)
                                .addComponent(LabelPE5M1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextPE5B, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextABM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTAB, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelTAB)
                                    .addComponent(LabelTCB))
                                .addGap(18, 18, 18)
                                .addComponent(jTextTCB, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttParar)
                    .addComponent(jTextAMB, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181)
                .addComponent(bttSeguir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTCM)
                    .addComponent(jTextTCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTCB)
                    .addComponent(jTextTCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTAM)
                    .addComponent(LabelTAB)
                    .addComponent(jTextTAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPasajerosM)
                    .addComponent(jTextPasajerosM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPasajerosB)
                    .addComponent(jTextPasajerosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelHangarM)
                            .addComponent(jTextHangarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextHangarB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAEM)
                    .addComponent(jTextAreaEstcM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextAreaEstcB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTallerM)
                    .addComponent(jTextTallerM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTallerB)
                    .addComponent(jTextTallerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPE1M)
                    .addComponent(jTextPE1M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPE4M)
                    .addComponent(jTextPE4M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPE1M1)
                    .addComponent(jTextPE1B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPE4M1)
                    .addComponent(jTextPE4B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPE2M)
                    .addComponent(jTextPE2M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPE5M)
                    .addComponent(jTextPE5M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPE2B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPE5M1)
                    .addComponent(jTextPE5B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPE2M1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelPE3M1)
                        .addComponent(jTextPE3B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextPE6M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelPE3M)
                        .addComponent(jTextPE3M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelPE6M))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelPE6M1)
                        .addComponent(jTextPE6B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelARM)
                            .addComponent(jTextARM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextARB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelARM1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelP1M)
                    .addComponent(LabelP3M)
                    .addComponent(jTextP1M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextP3M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelP1M1)
                    .addComponent(LabelP3M1)
                    .addComponent(jTextP3B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextP1B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAbelP2M)
                    .addComponent(jTextP2M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelP4M)
                    .addComponent(jTextP4M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LAbelP2M1)
                    .addComponent(jTextP2B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelP4M1)
                    .addComponent(jTextP4B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAMB)
                    .addComponent(LabelABM))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextABM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttParar)
                    .addComponent(bttSeguir))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextHangarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHangarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHangarMActionPerformed

    private void jTextAreaEstcMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAreaEstcMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaEstcMActionPerformed

    private void jTextHangarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHangarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHangarBActionPerformed

    private void jTextTCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTCMActionPerformed

    private void bttPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPararActionPerformed
        // TODO add your handling code here:
        superior.detener();
    }//GEN-LAST:event_bttPararActionPerformed

    private void bttSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSeguirActionPerformed
        // TODO add your handling code here:
        superior.reanudar();
    }//GEN-LAST:event_bttSeguirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parte1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parte1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parte1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parte1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    new Parte1().setVisible(true);
                }catch (RemoteException e){
                    
                }
                
            }
        });
    }
    
    public void iniciarServidorMadrid() throws RemoteException{
        try{
            ServidorAeropuerto obj = new ServidorAeropuerto();
            Registry registro = LocateRegistry.createRegistry(1099);
            Naming.rebind("//127.0.0.1/ObjetoAeropuertoM", obj);
            obj.obtenerAeropuerto(aeroM);
        }catch (Exception e){}
    }
    
    public void iniciarServidorBarcelona() throws RemoteException{
        try{
            ServidorAeropuerto obj = new ServidorAeropuerto();
            Registry registro = LocateRegistry.createRegistry(1099);
            Naming.rebind("//127.0.0.1/ObjetoAeropuertoB", obj);
            obj.obtenerAeropuerto(aeroM);
        }catch (Exception e){}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAbelP2M;
    private javax.swing.JLabel LAbelP2M1;
    private javax.swing.JLabel LabelABM;
    private javax.swing.JLabel LabelAEM;
    private javax.swing.JLabel LabelAMB;
    private javax.swing.JLabel LabelARM;
    private javax.swing.JLabel LabelARM1;
    private javax.swing.JLabel LabelHangarM;
    private javax.swing.JLabel LabelP1M;
    private javax.swing.JLabel LabelP1M1;
    private javax.swing.JLabel LabelP3M;
    private javax.swing.JLabel LabelP3M1;
    private javax.swing.JLabel LabelP4M;
    private javax.swing.JLabel LabelP4M1;
    private javax.swing.JLabel LabelPE1M;
    private javax.swing.JLabel LabelPE1M1;
    private javax.swing.JLabel LabelPE2M;
    private javax.swing.JLabel LabelPE2M1;
    private javax.swing.JLabel LabelPE3M;
    private javax.swing.JLabel LabelPE3M1;
    private javax.swing.JLabel LabelPE4M;
    private javax.swing.JLabel LabelPE4M1;
    private javax.swing.JLabel LabelPE5M;
    private javax.swing.JLabel LabelPE5M1;
    private javax.swing.JLabel LabelPE6M;
    private javax.swing.JLabel LabelPE6M1;
    private javax.swing.JLabel LabelPasajerosB;
    private javax.swing.JLabel LabelPasajerosM;
    private javax.swing.JLabel LabelTAB;
    private javax.swing.JLabel LabelTAM;
    private javax.swing.JLabel LabelTCB;
    private javax.swing.JLabel LabelTCM;
    private javax.swing.JLabel LabelTallerB;
    private javax.swing.JLabel LabelTallerM;
    private javax.swing.JButton bttParar;
    private javax.swing.JButton bttSeguir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextABM;
    private javax.swing.JTextField jTextAMB;
    private javax.swing.JTextField jTextARB;
    private javax.swing.JTextField jTextARM;
    private javax.swing.JTextField jTextAreaEstcB;
    private javax.swing.JTextField jTextAreaEstcM;
    private javax.swing.JTextField jTextHangarB;
    private javax.swing.JTextField jTextHangarM;
    private javax.swing.JTextField jTextP1B;
    private javax.swing.JTextField jTextP1M;
    private javax.swing.JTextField jTextP2B;
    private javax.swing.JTextField jTextP2M;
    private javax.swing.JTextField jTextP3B;
    private javax.swing.JTextField jTextP3M;
    private javax.swing.JTextField jTextP4B;
    private javax.swing.JTextField jTextP4M;
    private javax.swing.JTextField jTextPE1B;
    private javax.swing.JTextField jTextPE1M;
    private javax.swing.JTextField jTextPE2B;
    private javax.swing.JTextField jTextPE2M;
    private javax.swing.JTextField jTextPE3B;
    private javax.swing.JTextField jTextPE3M;
    private javax.swing.JTextField jTextPE4B;
    private javax.swing.JTextField jTextPE4M;
    private javax.swing.JTextField jTextPE5B;
    private javax.swing.JTextField jTextPE5M;
    private javax.swing.JTextField jTextPE6B;
    private javax.swing.JTextField jTextPE6M;
    private javax.swing.JTextField jTextPasajerosB;
    private javax.swing.JTextField jTextPasajerosM;
    private javax.swing.JTextField jTextTAB;
    private javax.swing.JTextField jTextTAM;
    private javax.swing.JTextField jTextTCB;
    private javax.swing.JTextField jTextTCM;
    private javax.swing.JTextField jTextTallerB;
    private javax.swing.JTextField jTextTallerM;
    // End of variables declaration//GEN-END:variables
}
